var clubs = [
  {
    "code": "---",
    "logo": "default.jpg",
    "name": "- - -",
    "color": "#FFFFFF",
  },
  {
    "code": "ALV",
    "logo": "ALV.png",
    "name": "Alaves",
    "color": "#0761AF",
    "initial": "A",
  },
  {
    "code": "UDA",
    "logo": "UDA.png",
    "name": "Almeria",
    "color": "#ee1119",
    "initial": "A",
  },
  {
    "code": "ATB",
    "logo": "ATB.png",
    "name": "Athletic Bilbao",
    "color": "#EE2523",
    "initial": "A",
  },
  {
    "code": "ATM",
    "logo": "ATM.png",
    "name": "Atletico de Madrid",
    "color": "#272E61",
    "initial": "A",
  },
  {
    "code": "FCB",
    "logo": "FCB.png",
    "name": "FC Barcelona",
    "color": "#EDBB00",
    "initial": "B",
  },
  {
    "code": "BET",
    "logo": "BET.png",
    "name": "Real Betis",
    "color": "#0BB363",
    "initial": "B",
  },
  {
    "code": "CLV",
    "logo": "CLV.png",
    "name": "Celta de Vigo",
    "color": "#8AC3EE",
    "initial": "C",
  },
  {
    "code": "CCF",
    "logo": "CCF.png",
    "name": "Cadiz",
    "color": "#fde607",
    "initial": "C",
  },
  {
    "code": "GET",
    "logo": "GET.png",
    "name": "Getafe",
    "color": "#005999",
    "initial": "G",
  },
  {
    "code": "GIR",
    "logo": "GIR.png",
    "name": "Girona",
    "color": "#cd2534",
    "initial": "G",
  },
  {
    "code": "GCF",
    "logo": "GCF.png",
    "name": "Granada",
    "color": "#A61B2B",
    "initial": "G",
  },
  {
    "code": "LAP",
    "logo": "LAP.png",
    "name": "Las Palmas",
    "color": "#004b9d",
    "initial": "P",
  },
  {
    "code": "RCD",
    "logo": "RCD.png",
    "name": "Mallorca",
    "color": "#E20613",
    "initial": "M",
  },
  {
    "code": "OSA",
    "logo": "OSA.png",
    "name": "Osasuna",
    "color": "#0A346F",
    "initial": "O",
  },
  {
    "code": "SOC",
    "logo": "SOC.png",
    "name": "Real Sociedad",
    "color": "#0067B1",
    "initial": "R",
  },
  {
    "code": "RAY",
    "logo": "RAY.png",
    "name": "Rayo Vallecano",
    "color": "#eaaf10",
    "initial": "R",
  },
  {
    "code": "MAD",
    "logo": "MAD.png",
    "name": "Real Madrid",
    "color": "#FEBE10",
    "initial": "M",
  },
  {
    "code": "SEV",
    "logo": "SEV.png",
    "name": "Sevilla",
    "color": "#F43333",
    "initial": "S",
  },
  {
    "code": "VAL",
    "logo": "VAL.png",
    "name": "Valencia",
    "color": "#0097D7",
    "initial": "V",
  },
  {
    "code": "VIL",
    "logo": "VIL.png",
    "name": "Villarreal",
    "color": "#FFE667",
    "initial": "V",
  }
];
